export const ENTERPRISE_RUNTIME_METHOD = "enterprise.runtime.run";
export const ENTERPRISE_RUNTIME_SESSION_NAMESPACE = "enterprise-runtime";

export const ENTERPRISE_RUNTIME_CONFIG_SNAPSHOT_DIR = "config-snapshots";
export const ENTERPRISE_RUNTIME_DEFAULT_LOGS_ENV = "OPENCLAW_ENTERPRISE_RUNTIME_LOGS_DIR";
export const ENTERPRISE_RUNTIME_DEFAULT_TMP_ENV = "OPENCLAW_ENTERPRISE_RUNTIME_TMP_ROOT";
export const ENTERPRISE_RUNTIME_LEGACY_LOGS_ENV = "OPENCLAW_RUNTIME_LOGS_DIR";
export const ENTERPRISE_RUNTIME_LEGACY_TMP_ENV = "OPENCLAW_RUNTIME_TMP_ROOT";
