MAX_VIDEO_BYTES = 500 * 1024 * 1024
DEFAULT_MAX_DOWNLOAD_BYTES = MAX_VIDEO_BYTES
DEFAULT_MAX_MODEL_VIDEO_BYTES = 50 * 1024 * 1024
DEFAULT_MAX_VIDEO_DURATION_SECONDS = 0
DEFAULT_MAX_VIDEO_FRAMES = 0
DEFAULT_VIDEO_UNDERSTANDING_FPS = 3.0
MIN_VIDEO_UNDERSTANDING_FPS = 0.2
MAX_VIDEO_UNDERSTANDING_FPS = 5.0
